# Generated by Django 5.2.6 on 2025-11-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
