# Generated by Django 5.2.6 on 2025-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0003_pendingcategory_item_pending_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_hold', 'On Hold')], default='available', max_length=20),
        ),
    ]
