# Generated by Django 5.2.6 on 2025-11-20 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0005_item_held_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='held_by',
        ),
        migrations.AddField(
            model_name='item',
            name='held_by',
            field=models.ManyToManyField(blank=True, related_name='held_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
