# Generated by Django 5.2.6 on 2025-11-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0006_remove_item_status_remove_item_held_by_item_held_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_in_repository',
            field=models.BooleanField(default=False),
        ),
    ]
