# Generated by Django 5.2.6 on 2025-11-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0007_item_is_in_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
