# Generated by Django 5.2.8 on 2025-11-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0009_item_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='found_date',
            field=models.DateField(verbose_name='date found'),
        ),
    ]
