# Generated by Django 5.2.6 on 2025-11-29 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0010_alter_item_found_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_in_repository',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_retrieved',
        ),
        migrations.AddField(
            model_name='item',
            name='retrieved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('not_at_repository', 'Not at Repository'), ('at_repository', 'At Repository'), ('retrieved', 'Retrieved')], default='not_at_repository', max_length=20),
        ),
    ]
