# Generated by Django 5.2.6 on 2025-12-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0011_remove_item_is_in_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lnf.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lnf.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='found_date',
            field=models.DateField(db_index=True, verbose_name='date found'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('not_at_repository', 'Not at Repository'), ('at_repository', 'At Repository'), ('retrieved', 'Retrieved')], db_index=True, default='not_at_repository', max_length=20),
        ),
    ]
