# Generated by Django 5.2.6 on 2026-01-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0012_alter_category_parent_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
