# Generated by Django 5.2.8 on 2026-01-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0014_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='pendingcategory',
            options={'verbose_name_plural': 'pending categories'},
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('not_at_repository', 'Not at Prefect Office'), ('at_repository', 'At Prefect Office'), ('retrieved', 'Retrieved')], db_index=True, default='not_at_repository', max_length=20),
        ),
    ]
